[server]
headless = true
port = 10000

[browser]
serverAddress = "127.0.0.1"
serverPort = 10000 


[theme]
primaryColor="#029dd0"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"